// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DisplayInfoBar
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDisplayInfoBarPackageString = "67e4471b-024c-4b1b-9c7e-02c31f985afe";
        public static Guid guidDisplayInfoBarPackage = new Guid(guidDisplayInfoBarPackageString);

        public const string guidDisplayInfoBarPackageCmdSetString = "17c3d91a-eb4d-4bcf-bd9c-fcfcd922a005";
        public static Guid guidDisplayInfoBarPackageCmdSet = new Guid(guidDisplayInfoBarPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowWithInfoBarCommandId = 0x0100;
    }
}