// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonToCSharpCodeGeneration
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJsonToCSharpCodeGenerationPackageString = "7f598ea7-ac90-4b85-b961-c2adaaa3b542";
        public static Guid guidJsonToCSharpCodeGenerationPackage = new Guid(guidJsonToCSharpCodeGenerationPackageString);

        public const string guidVisibilityContextString = "878bc455-61ba-459b-b18d-6922cde6ce19";
        public static Guid guidVisibilityContext = new Guid(guidVisibilityContextString);

        public const string guidJsonToCSharpCodeGenerationPackageCmdSetString = "25cc0502-dddc-4d0e-8d04-9ceeef853fd3";
        public static Guid guidJsonToCSharpCodeGenerationPackageCmdSet = new Guid(guidJsonToCSharpCodeGenerationPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ApplyCodeGenerationCommandId = 0x0100;
    }
}