// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExternalSearch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExternalSearchPackageString = "d7dd46cf-a0df-40d1-9a59-9bf15236077c";
        public static Guid guidExternalSearchPackage = new Guid(guidExternalSearchPackageString);

        public const string guidExternalSearchPackageCmdSetString = "fc8acfab-bbb4-4764-992a-7e2897e9e534";
        public static Guid guidExternalSearchPackageCmdSet = new Guid(guidExternalSearchPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SearchCommandId = 0x0100;
    }
}