// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PropertiesToolWindow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPropertiesToolWindowPackageString = "78842caa-c570-4d70-aba5-c3a97c60ad3e";
        public static Guid guidPropertiesToolWindowPackage = new Guid(guidPropertiesToolWindowPackageString);

        public const string guidPropertiesToolWindowPackageCmdSetString = "8324e1cf-43a5-4273-b87a-936a10d323af";
        public static Guid guidPropertiesToolWindowPackageCmdSet = new Guid(guidPropertiesToolWindowPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowCommandId = 0x0100;
    }
}